# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ado-theme"
license = "MIT"
licenselink = "https://github.com/arresteddevops/ado-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/arresteddevops/ado-theme"
tags = []
features = []
min_version = 0.19
theme_version = 0.1.1


[author]
  name = "Matt Stratton"
  homepage = "https://www.mattstratton.com"
